name: Python Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build -p windows-capture-python --verbose --release

    - name: Upload all wheels
      uses: actions/upload-artifact@v4
      with:
        name: windows-capture
        path: ./target/release/*

    - name: Run tests
      run: cargo test -p windows-capture-python --verbose
