name: Rust

on:
  push:
    branches: ["main"]
    branches: ["main"]
  pull_request:
    branches: ["main"]
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
